name:                lambda-pie
version:             0.1.0.0
github:              "https://github.com/Taskkill/lambda-pie"
license:             BSD3
author:              "Taskkill"
maintainer:          "example@example.com"
copyright:           "2021 Taskkill"

extra-source-files:
- README.md
- ChangeLog.md
- src/Simply/Parser/Lexer.x
- src/Simply/Parser/Parser.y

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/Taskkill/lambda-pie

dependencies:
- base >= 4.7 && < 5
- mtl
- array
- utf8-string
- containers >= 0.6.2.1
- hspec

library:
  source-dirs: src

executables:
  simply:
    main:               Main.hs
    source-dirs:        app/simply
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pie

  systemf:
    main:               Main.hs
    source-dirs:        app/systemF
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pie

  dependently:
    main:               Main.hs
    source-dirs:        app/dependently
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pie

  lambda-pie-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pie

tests:
  lambda-pie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pie
